### ISSUE TITLE
Move here docker deployment and examples

### ISSUE THREAD

**Issue by luis100** [keeps/dbptk-enterprise#1]
Move it from https://github.com/keeps/db-visualization-toolkit

Readme should also contain deploy instruction for docker copyed from the base repo

**Comment by luis100** [comment]
Setup build using travis or docker hub

**Comment by luis100** [comment]
Dockerfile needs to get war from bintray.
Make release for:
* latest: every commit in master
* vX.X.X: every new tag

**Comment by 006627** [comment]
Done, build configurations was made in [docker hub](https://cloud.docker.com/u/keeps/repository/docker/keeps/dbvtk/builds)
