### ISSUE TITLE
Authentication using RODA

### ISSUE THREAD

**Issue by finnove** [keeps/dbptk-enterprise#10]
Trying out RODA and DBPTK, and want some basic authentication.

Can DBPTK authenticate using RODA? How? Tried to follow [this](https://github.com/keeps/dbptk-ui/wiki/Configuration), changing 
`ui.filter.internal.enabled = true`
`ui.filter.internal.server = http://localhost:8082`
I just get a dialog box saying I need to authenticate, but nothing more happens.

I have roda running on http://localhost:8082 and dbptk running on http://localhost:8081
I also see there is a plugin called roda-dbptk-plugin - is it necessary here, and how to use it?

**Comment by luis100** [comment]
Hello, DBPTK can only integrate with [CAS](https://apereo.github.io/cas/) authentication, which can then integrate or delegate to many authentication systems.

RODA can also integrate with CAS for authentication and use external authentication providers.

Finally, RODA can also internally manage users. There is an option in RODA to expose this users as an LDAP server, and CAS can be configured to use the LDAP server as a authentication provider. DBPTK can then be integrated with this CAS instance to authenticate against the users defined in RODA.

The roda-dbptk-plugin is to automatically load SIARD files archived in RODA into DBPTK Enteprise. For the last version of DBPTK Enterprise, you must use the commercial version of the plugin, which is available by contacting sales@keep.pt.
