### ISSUE TITLE
Is there an external interface to DBPTK enterprise?

### ISSUE THREAD

**Issue by gdubya** [keeps/dbptk-enterprise#12]
We're interested in the idea of using a tool such as PrestoDB to explore our SIARD files. One way to achieve this would be to connect Presto to DBPTK.

Is it possible to use DBPTK enterprise via an API? It looks like there's a REST API but I could not find any documentation for it.

Alternatively perhaps we could create [a Thrift specification](https://thrift.apache.org/) with DBPTK and use [the PrestoDB thrift connector](https://prestodb.io/docs/current/connector/thrift.html)?

**Comment by gdubya** [comment]
Edit: I found the Swagger documentation for the REST API. So the question now is: is there an alternative to REST?

**Comment by luis100** [comment]
If you want to use SQL to query information in SIARD than it makes no sense to use DBPTK Enterprise at all as the whole point is to load information into a Solr backend and allow Google-like query on it.

For the purpose you are proposing, I would highly recommend using DBPTK Developer or DBPTK Desktop to load the SIARD file into a Database Management System like MySQL or PostgreSQL (or something even lighter with a JDBC interface), and then using this backend to connect to your PrestoDB query system.

Note that for DBPTK Enterprise to allow search on the SIARD content it would need to load the SIARD content into a Solr backend anyway, so replacing this with a DBMS system wouldn't be less efficient.

**Comment by gdubya** [comment]
Thanks for the input! That sounds like a good idea. I'm not very experienced with DBPTK yet so I wasn't aware of the alternatives. 😄
