### ISSUE TITLE
Cannot load siard with LOBs stored outside from siard

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-enterprise#14]
If you try to load a database from siard into the DBPTK Enterprise that has lob folders additionally to siard file itself then these files will never reach the Enterprise...

![image](https://user-images.githubusercontent.com/3479156/108351140-c9b1e980-71ed-11eb-8516-a6b25406c024.png)

For example you know that Sakila has text LOB in the table film_text in column description. But there is nothing here:
![image](https://user-images.githubusercontent.com/3479156/108351287-fb2ab500-71ed-11eb-86db-d58b315b0d36.png)

Log file of DBPTK Enterprise is also screaming that lobs can not be found.

**Comment by hmiguim** [comment]
We are aware of situations like this.

If you are using a docker-compose type of deploy please follow this steps:

1. Update dbvtk-viewer.properties file and set manage.upload.basePath property with a path to the SIARD folder, for instance, /volumes/siards
2.  Map the volume correctly; if in the previous point you said that manage.upload.basePath=/volumes/siards the docker-compose most have the volume mapped like this: /path/to/the/folder/where/siard/is:/volumes/siards:ro
3. Replace the <siardFilename> with the name of the SIARD then run: curl -X POST "http://localhost:8080/api/v1/database" -H "accept: text/plain" -H "Content-Type: application/json" -d "<siardFilename>"

Then when you load the SIARD data it is now aware where the external files are located
