### ISSUE TITLE
Unabe to deploy using Docker App

### ISSUE THREAD

**Issue by domenicoruggeri** [keeps/dbptk-enterprise#2]
Description: 
On Windows, I have followed the steps on https://visualization.database-preservation.com/ to "Deploy using Docker App", so I have installed docker, docker-compose and docker-app, however I am not able to "render" the dbvtk because I am getting the follownig error when trying "To execute in a docker-compose":
"Error: cannot locate application "keeps/dbvtk-app:latest" in filesystem or registry: manifest unknown: manifest unknown".

I have also tried to simply do "docker pull keeps/dbvkt" or "docker pull keeps/dbvkt-app" and got: "Error response from daemon: pull access denied for keeps/dbvkt, repository does not exist or may require 'docker login".

Browser (Internet explorer, Chrome, Firefox, etc):

Browser version:

Steps required to reproduce the bug:

1. Install docker, docker-compose and docker-app
2. run PowerShell as admin and type "docker-app render keeps/dbvtk-app:latest | docker-compose -f - up" 
3.  If point 2 fails, test you can pull the repo on docker-hub. Within the same PowerShell type: "docker pull keeps/dbvtk" or "docker pull keeps/dbvtk-app"  

Attach any related screenshots below.

**Comment by 006627** [comment]
@domenicoruggeri a new image was uploaded on docker hub, please reopen this issue if you need.
