### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Jai-tatum** [keeps/dbptk-enterprise#22]
I'm having trouble understanding how to install this program. I am also trying to make an automated install with MECM so any tips would be helpful. Thank you.

How do I "Open a terminal within deploys/development folder" and "Run docker-compose up". Do I do these in the docker app somehow, or on the command line?

**Comment by luis100** [comment]
A "terminal" here refers to the command line. The "docker compose" is a more complex setup than the simple docker app.

Check the following links:
https://docs.docker.com/compose/
https://linuxhint.com/beginners_guide_docker_compose/

Also, please note that the compose requires Linux or macOS to run, you cannot run our docker compose configuration in Windows without changes.
