### ISSUE TITLE
No access to `cas-file` docker image

### ISSUE THREAD

**Issue by omBratteng** [keeps/dbptk-enterprise#23]
Hello,

When trying to run `docker-compose up`, we get access forbidden when trying to pull the `cas-file` docker image.
I believe it is related to this change https://github.com/keeps/dbptk-enterprise/commit/3b47e3d9fbe60cc9d6e94e773a243149d9512462#diff-034aa0ff3e6f391b9a43795ac0f48b842a2ce2abdc1de092eb4ed7ba8adb7c97L29-R35, where you change from building the image locally, to pulling from remote.

**Comment by powerbyte00** [comment]
Hello,
Same issue with me as well, for the CAS image: **docker.labs.keep.pt/common/cas/cas-file:6.5.3** (in the file docker-compose.yml), when you run docker-compose up, it says: "Error response from daemon: Head https://docker.labs.keep.pt/v2/common/cas/cas-file/manifests/6.5.3: denied: access forbidden". Please advise.
