### ISSUE TITLE
Failure when "building" image with docker-compose up, could not resolve all files for :classpath

### ISSUE THREAD

**Issue by sazzor** [keeps/dbptk-enterprise#24]
=> ERROR [overlay 8/8] RUN cd cas-overlay     && ./gradlew clean build --parallel --no-daemon     && ./gradlew   15.7s
------
 > [overlay 8/8] RUN cd cas-overlay     && ./gradlew clean build --parallel --no-daemon     && ./gradlew createKeystore:
#0 1.083 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.6/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#0 1.874 Daemon will be stopped at the end of the build
#0 2.074 Configuration on demand is an incubating feature.
#0 15.07
#0 15.07 FAILURE: Build failed with an exception.
#0 15.07
#0 15.07 * What went wrong:
#0 15.08 A problem occurred configuring root project 'cas'.
#0 15.08 > Could not resolve all files for configuration ':classpath'.
#0 15.08    > Could not find gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.3.1.
#0 15.08      Searched in the following locations:
#0 15.08        - file:/root/.m2/repository/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.3.1/jib-gradle-plugin-3.3.1.pom
#0 15.08        - https://repo.maven.apache.org/maven2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.3.1/jib-gradle-plugin-3.3.1.pom
#0 15.08        - https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.3.1/jib-gradle-plugin-3.3.1.pom
#0 15.08        - https://repo.spring.io/milestone/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.3.1/jib-gradle-plugin-3.3.1.pom
#0 15.08      Required by:
#0 15.08          project :

**Comment by sazzor** [comment]
Same error in docker-desktop (Windows) and Ubuntu Server

**Comment by hmiguim** [comment]
Fixed: https://github.com/keeps/dbptk-enterprise/commit/09848a7b05d30f9040774c3bad14fa2fcdf53acf
