### ISSUE TITLE
Link to github repo at https://github.com/keeps/db-visualization-toolkit/blob/master/README.md doesn't resolve.

### ISSUE THREAD

**Issue by pgoetz** [keeps/dbptk-enterprise#3]
The link to the Database Visualization Toolkit github page provided here:
  https://github.com/keeps/db-visualization-toolkit/blob/master/README.md

https://github.com/keeps/db-preservation-toolkit-docker

gives a 404 error.  The github repo is actually located here:

  https://github.com/keeps/db-visualization-toolkit-docker

**Comment by luis100** [comment]
fixed
