### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by domenicoruggeri** [keeps/dbptk-enterprise#6]
Hi,

I have cloned the master branch, downloaded the .yml file and run the docker-compose up within the project folder... but it results in solr failing at some point with the following cause: 

_solr_1   | 2020-03-14 22:50:07.045 ERROR (qtp176683244-19) [c:dbv-databases s:shard1 r:core_node2 x:dbv-databases_shard1_replica_n1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Error CREATEing SolrCore 'dbv-databases_shard1_replica_n1': Unable to create core [dbv-databases_shard1_replica_n1] Caused by: solr.NestPathField
solr_1   |      at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1136)
solr_1   |      at org.apache.solr.handler.admin.CoreAdminOperation.lambda$static$0(CoreAdminOperation.java:92)
solr_1   |      at org.apache.solr.handler.admin.CoreAdminOperation.execute(CoreAdminOperation.java:360)
solr_1   |      at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:396)
solr_1   |      at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:180)
solr_1   |      at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
solr_1   |      at org.apache.solr.servlet.HttpSolrCall.handleAdmin(HttpSolrCall.java:736)
solr_1   |      at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:717)
solr_1   |      at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:496)
solr_1   |      at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:395)
solr_1   |      at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:341)
solr_1   |      at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
solr_1   |      at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
solr_1   |      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
solr_1   |      at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
solr_1   |      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1   |      at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
solr_1   |      at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
solr_1   |      at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
solr_1   |      at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
solr_1   |      at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
solr_1   |      at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
solr_1   |      at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
solr_1   |      at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
solr_1   |      at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
solr_1   |      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
solr_1   |      at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
solr_1   |      at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
solr_1   |      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1   |      at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
solr_1   |      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1   |      at org.eclipse.jetty.server.Server.handle(Server.java:502)
solr_1   |      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
solr_1   |      at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
solr_1   |      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
solr_1   |      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
solr_1   |      at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
solr_1   |      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
solr_1   |      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
solr_1   |      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
solr_1   |      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
solr_1   |      at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
solr_1   |      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
solr_1   |      at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
solr_1   |      at java.base/java.lang.Thread.run(Thread.java:834)
solr_1   | Caused by: org.apache.solr.common.SolrException: Unable to create core [dbv-databases_shard1_replica_n1]
solr_1   |      at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1208)
solr_1   |      at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1097)
solr_1   |      ... 44 more
solr_1   | Caused by: org.apache.solr.common.SolrException: Could not load conf for core dbv-databases_shard1_replica_n1: Can't load schema managed-schema: Plugin init failure for [schema.xml] fieldType "_nest_path_": Error loading class 'solr.NestPathField'
solr_1   |      at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:97)
solr_1   |      at org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1236)
solr_1   |      at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1183)
solr_1   |      ... 45 more
solr_1   | Caused by: org.apache.solr.common.SolrException: Can't load schema managed-schema: Plugin init failure for [schema.xml] fieldType "_nest_path_": Error loading class 'solr.NestPathField'
solr_1   |      at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:590)
solr_1   |      at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:180)
solr_1   |      at org.apache.solr.schema.ManagedIndexSchema.<init>(ManagedIndexSchema.java:105)
solr_1   |      at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:173)
solr_1   |      at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:45)
solr_1   |      at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
solr_1   |      at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:119)
solr_1   |      at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:92)
solr_1   |      ... 47 more
solr_1   | Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "_nest_path_": Error loading class 'solr.NestPathField'
solr_1   |      at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:182)
solr_1   |      at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:481)
solr_1   |      ... 54 more
solr_1   | Caused by: org.apache.solr.common.SolrException: Error loading class 'solr.NestPathField'
solr_1   |      at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:557)
solr_1   |      at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:626)
solr_1   |      at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:591)
solr_1   |      at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:584)
solr_1   |      at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:90)
solr_1   |      at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:53)
solr_1   |      at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:152)
solr_1   |      ... 55 more
solr_1   | Caused by: java.lang.ClassNotFoundException: solr.NestPathField
solr_1   |      at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
solr_1   |      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
solr_1   |      at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899)
solr_1   |      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
solr_1   |      at java.base/java.lang.Class.forName0(Native Method)
solr_1   |      at java.base/java.lang.Class.forName(Class.java:398)
solr_1   |      at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:541)
solr_1   |      ... 61 more_

Which I believe is the cause of the embedded Tomcat also failing to start: _org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat_

Before running the docker-compose up I also made sure there are no other containers, it is a clean environment.

I really appreciate any help as I stuck at this point.

Many thanks in advance,
Dom

**Comment by 006627** [comment]
Hello, 
Please update Solr version from 7.7 to 8.4.1 on docker-compose.yml file, I will update the file in repository as soon as possible.

**Comment by domenicoruggeri** [comment]
Thanks a lot for your prompt reply. 
It's been deployed successfully now, thank you!
