### ISSUE TITLE
Development deployment not working

### ISSUE THREAD

**Issue by domenicoruggeri** [keeps/dbptk-enterprise#7]
Hi,

I have deployed my copy of dbvtk, but when browsing to localhost:8080 I am prompt with this page:

![image](https://user-images.githubusercontent.com/40301221/76861048-e1e9ed80-6853-11ea-863c-3a3117c6db87.png)

There is nothing I can do in this page. Am I missing some setting or is there a different URL I should navigate to?

I've also tried to click on the Login, but the link is apparently broken.

Thanks a lot in advance for your help,
Dom

**Comment by luis100** [comment]
New version now requires authentication, which requires [Apereo CAS](https://hub.docker.com/r/apereo/cas/) installed and configured with a local (file) user configuration, or an external authentication system configured (ldap, oauth, google, etc.).

Currently deployment example is outdated and needs to include this new component and also  configuration to integrate DBPTK Enterprise with Apereo CAS that can be setup in the same docker-compose.

**Comment by domenicoruggeri** [comment]
Thanks for your reply @luis100 . 
In the meantime this gets fixed, is there a specific version you would recommend to use instead?

Thanks in advance.

**Comment by luis100** [comment]
In the meantime I recommend you to use [DBPTK Desktop](https://database-preservation.com/#desktop).

**Comment by luis100** [comment]
Hello, I've updated the code so it uses the staging version of DBPTK Enterprise which now allows to function without the CAS authentication system plugged in. Please try it out.

**Comment by domenicoruggeri** [comment]
Hi, when cloning the latest version of the code I have noticed the folder deploys/deployment does not contain the "cas" folder. Do I have to keep it like it is?

I tried as it is, without it and I am now getting that old error "html is null". Since that one has been previously fixed by moving the "cas" folder contained deeploys/development up to the top level, I have also tried to do the same using the content of the cas folder of the previous version of code... unfortunately without getting any further.

![image](https://user-images.githubusercontent.com/40301221/78368212-2e0a9100-75bb-11ea-8f30-4dc947bd1de3.png)

**Comment by luis100** [comment]
It seems you are not correctly loading the configuration file. Are you running in Windows machine? If so it might be a problem of paths because on this line I am using Unix-style paths which might be incompatible with a Windows host machine.

https://github.com/keeps/db-visualization-toolkit-docker/blob/master/deploys/development/docker-compose.yml#L12

**Comment by domenicoruggeri** [comment]
No, I am running in a Linux machine. 
The link you provided, is it the docker-compose.yml I should be using?

**Comment by hmiguim** [comment]
Yes, please use that file. The staging image on docker hub was also updated please pull it.

**Comment by domenicoruggeri** [comment]
Thanks both of you for your help. The latest commits have fixed the issue. Will close it.
