### ISSUE TITLE
Problems with docker compose up

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/dbptk-enterprise#8]
I haven't succeeded to run a flawless `docker-compose up` command.
I get a long list of steps that run okay, and a lot of warnings and errors but I am not skilled enough to understand what is wrong.
[report.txt](https://github.com/keeps/db-visualization-toolkit-docker/files/4563711/report.txt)

**Comment by 006627** [comment]
Hi @PhillipTommerholt, 
It looks like your docker-compose file is out of date, through the report you can see that the version of the Solr being used is an old one (7.7).

Could you please update the [docker-compose](https://github.com/keeps/db-visualization-toolkit-docker/tree/master/deploys/development) and check if the problem persists? (you need to download the Config folder as well)

**Comment by PhillipTommerholt** [comment]
Thanks for helping.
I updated the docker-compose.yml but now I am getting almost nowhere:
![image](https://user-images.githubusercontent.com/15984159/81059258-678f2e80-8ed0-11ea-8fc4-43129104e694.png)

**Comment by 006627** [comment]
Hi @PhillipTommerholt, this problem is related to the docker configuration on windows.
Please enable [disk sharing](https://docs.docker.com/docker-for-windows/troubleshoot/#volume-mounting-requires-shared-drives-for-linux-containers) through the Docker application.

Let me know if you need help

**Comment by PhillipTommerholt** [comment]
Thanks a lot! It worked
Sadly I ran into a showstopper - I do not have enough memory at my current machine. But thanks for helping.
