### ISSUE TITLE
[NullPointerException] html is null

### ISSUE THREAD

**Issue by ghost** [keeps/dbptk-enterprise#9]
Hi db-visualization-toolkit-docker. I have succeed in running the `docker-compose up` command. Everything seems to be working, but when I try to access "http://localhost:8080" i get an "Unexpected Error" saying "[NullPointerException] html is null". What to do?

**Comment by hmiguim** [comment]
Hi @mennskr,

That was a problem very similar  that was fixed in the version 2.4.1. https://github.com/keeps/db-visualization-toolkit/issues/207.

Please check the image you are running and do a docker pull of the latest one. 

Tell me if that fixed your problem

**Comment by ghost** [comment]
He @hmiguim 

I would love to do that, but I don't know how to. Can you help me with som quick instructions?

**Comment by ghost** [comment]
`docker image inspect keeps/dbvtk`

return

`"Id": "sha256:47d2c207569da6e1d8b55ba349501dbe5ac399cd97a0131a79408463f45091ae",
        "RepoTags": [
            "keeps/dbvtk:latest"
        ],
        "RepoDigests": [
            "keeps/dbvtk@sha256:74cf17a3f2f13b66947fff6be391d87cf003d1ec4b952b71d6ae6ea03eac616d"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-04-20T11:34:06.838191799Z",`

**Comment by luis100** [comment]
Could you provide the output of http://localhost:8080/version.json

**Comment by ghost** [comment]
I did a `docker pull keeps/dbvtk:latest` but sadly it did not change anything

**Comment by luis100** [comment]
Note that this problem was originally due to a property missing from the file `dbvtk-viewer.properties` in configuration:
```properties
ui.header.title=<img src="api/v1/theme?resource_id=dbptk_logo_white_vector.svg" class="header-logo"><span class="header-text">DBPTK Enterprise</span>
```

**Comment by ghost** [comment]
`{"git.build.user.email":"travis@example.org","git.build.host":"localhost","git.dirty":"true","git.remote.origin.url":"https://github.com/keeps/db-visualization-toolkit.git","git.closest.tag.name":"v2.4.1","git.commit.id.describe-short":"v2.4.1","git.commit.user.email":"mguimaraes@keep.pt","git.commit.time":"2020-04-17T14:36:45+0000","git.commit.message.full":"Setting version 2.4.1","git.build.version":"2.4.1","git.commit.message.short":"Setting version 2.4.1","git.commit.id.abbrev":"63e9f48","git.branch":"63e9f48350e3d8a68680aa36bc63e7d43c0af9b9","git.build.user.name":"Travis CI User","git.closest.tag.commit.count":"0","git.commit.id.describe":"v2.4.1","git.commit.id":"63e9f48350e3d8a68680aa36bc63e7d43c0af9b9","git.tags":"v2.4.1","git.build.time":"2020-04-17T14:48:46+0000","git.commit.user.name":"mguimaraes"}`

**Comment by ghost** [comment]
I did check my `dbvtk-viewer.properties` for `ui.header.title`

```
##############################################
# Header
##############################################
ui.header.title=<img src="api/v1/theme?resource_id=dbptk_logo_white_vector.svg" class="header-logo"><span class="header-text">DBPTK Enterprise</span>
```

**Comment by luis100** [comment]
When the error appears, can you find a stack trace in the Javascript console?

**Comment by ghost** [comment]
![stack-trace](https://user-images.githubusercontent.com/60828410/81674713-eb579680-944d-11ea-89bb-25c815af0bf4.png)

**Comment by luis100** [comment]
NPE error happens at:
https://github.com/keeps/db-visualization-toolkit/blob/master/src/main/java/com/databasepreservation/server/client/main/MainPanel.java#L104

**Comment by ghost** [comment]
I reinstalled my computer with Windows. And installed Enterprise and then Desktop, and now everything is working. Sorry if the error was on my side. I really don't know, but I'm happy it's working.
